In [1]:
import numpy as np
import pandas as pd

In [2]:
from openai import OpenAI

In [25]:
client = OpenAI(
    base_url="http://192.168.15.182:1234/v1",
    api_key="sk-no-key-required"
)

In [26]:
response = client.chat.completions.create(
    model="qwen/qwen3.5-35b-a3b",
    messages=[
        {"role": "user", "content": "Привет! Напиши одно короткое приветствие."}
    ]
)

In [27]:
print(response.choices[0].message.content)

Привет! 😊

In [28]:
usage = response.usage

In [29]:
print(f"Токенов в запросе (Prompt): {usage.prompt_tokens}")
print(f"Токенов в ответе (Completion): {usage.completion_tokens}")
print(f"Всего потрачено токенов (Total): {usage.total_tokens}")

Токенов в запросе (Prompt): 23
Токенов в ответе (Completion): 1230
Всего потрачено токенов (Total): 1253

In [32]:
try:
    response = client.embeddings.create(
        model="qwen3.5-397b-a17b",
        input="Проверка embedding endpoint"
    )

    embedding = response.data[0].embedding

    print("Embedding endpoint works")
    print("Vector length:", len(embedding))
    print("First 5 values:", embedding[:5])

except Exception as e:
    print("Embedding endpoint failed")
    print(type(e).__name__)
    print(e)

Embedding endpoint failed
BadRequestError
Error code: 400 - {'error': "No models loaded. Please load a model in the developer page or use the 'lms load' command."}

In [48]:
usage = response.usage

In [49]:
print(f"Токенов в запросе (Prompt): {usage.prompt_tokens}")
print(f"Токенов в ответе (Completion): {usage.completion_tokens}")
print(f"Всего потрачено токенов (Total): {usage.total_tokens}")

Токенов в запросе (Prompt): 51
Токенов в ответе (Completion): 947
Всего потрачено токенов (Total): 998

In [50]:
print(response.choices[0].message.content)

* Массив — это структура данных, представляющая собой набор элементов одного типа, расположенных в непрерывной области памяти.
* Доступ по индексу выполняется за константное время O(1) благодаря возможности прямого вычисления адреса элемента.
* Адрес конкретного элемента рассчитывается по формуле: базовый адрес + (индекс × размер одного элемента).
* Отсутствие необходимости последовательного перехода от начала к нужному элементу обеспечивает высокую скорость чтения и записи.

In [3]:
df_qwen3539_answers = pd.read_csv("qwen35397ba17b_answers.csv", encoding="utf-8-sig")

In [5]:
df_qwen3539_answers.head(2)

,id,domain,source_type,source_id,source_url,question_type,difficulty,question,context,expected_answer,...,manual_final_score,manual_comment,model,temperature,latency_sec,created_at,prompt_tokens,completion_tokens,total_tokens,error
0,habr_879914_001,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое массив и как его элементы располагаю...,Раздел про массивы.,Массив хранит элементы одного типа в непрерывн...,...,NaN,NaN,qwen3.5-397b-a17b,0.0,110.255,2026-06-10T12:49:22,79.0,3330.0,3409.0,NaN
1,habr_879914_002,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,reasoning,medium,Почему доступ к элементу массива по индексу об...,Раздел про массивы и операции с ними.,Потому что адрес элемента можно вычислить напр...,...,NaN,NaN,qwen3.5-397b-a17b,0.0,128.601,2026-06-10T12:51:30,92.0,3891.0,3983.0,NaN

In [7]:
# Сохраняем в Excel
df_qwen3539_answers.to_excel("qwen35397ba17b_answers.xlsx", index=False)

In [8]:
df_qwen35vl_answers = pd.read_csv("qwen35vl122ba10bmlxcrack_answers.csv", encoding="utf-8-sig")

In [9]:
df_qwen35vl_answers.to_excel("qwen35vl122ba10bmlxcrack_answers.xlsx", index=False)

In [10]:
df_gemma_answers = pd.read_csv("gemma431bitmlx_answers.csv", encoding="utf-8-sig")

In [11]:
df_gemma_answers.to_excel("gemma431bitmlx_answers.xlsx", index=False)

In [12]:
# qwen/qwen3.5-35b-a3b
# Читаем Excel файл
df_qwen3535b = pd.read_excel(
    'llm_answers_30.xlsx',
    engine='openpyxl'
)

# Сохраняем в CSV
df_qwen3535b.to_csv(
    'qwen3535b_answers.csv', 
    index=False,
    encoding='utf-8-sig'
)

In [14]:
df_qwen3535b = pd.read_csv("qwenqwen3535b_answers.csv", encoding="utf-8-sig")

In [15]:
df_qwen3535b.head(2)

,id,domain,source_type,source_id,source_url,question_type,difficulty,question,context,expected_answer,...,manual_final_score,manual_comment,model,temperature,latency_sec,created_at,prompt_tokens,completion_tokens,total_tokens,error
0,habr_879914_001,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое массив и как его элементы располагаю...,Раздел про массивы.,Массив хранит элементы одного типа в непрерывн...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0,58.710,2026-06-09T17:33:21,79.0,3988.0,4067.0,NaN
1,habr_879914_002,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,reasoning,medium,Почему доступ к элементу массива по индексу об...,Раздел про массивы и операции с ними.,Потому что адрес элемента можно вычислить напр...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0,95.065,2026-06-09T17:34:56,92.0,6560.0,6652.0,NaN

In [16]:
df_qwen3535b.to_excel("qwen3535b_answers.xlsx", index=False)

### тест 35b qwen

In [9]:
df_test_qwen = pd.read_csv("qwenqwensmart.csv", encoding="utf-8-sig")

In [10]:
df_test_qwen

,id,domain,source_type,source_id,source_url,question_type,difficulty,question,context,expected_answer,...,manual_final_score,manual_comment,model,temperature,latency_sec,created_at,prompt_tokens,completion_tokens,total_tokens,error
0,habr_879914_001,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое массив и как его элементы располагаю...,Раздел про массивы.,Массив хранит элементы одного типа в непрерывн...,...,NaN,NaN,qwen3.5-397b-a17b,0.0,84.882,2026-06-11T17:10:45,83,2544,2627,NaN
1,habr_879914_002,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,reasoning,medium,Почему доступ к элементу массива по индексу об...,Раздел про массивы и операции с ними.,Потому что адрес элемента можно вычислить напр...,...,NaN,NaN,qwen3.5-397b-a17b,0.0,121.959,2026-06-11T17:12:47,96,3690,3786,NaN
2,habr_879914_003,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,comparison,easy,В чем основное отличие статического массива от...,Раздел про массивы.,"Статический массив имеет фиксированный размер,...",...,NaN,NaN,qwen3.5-397b-a17b,0.0,114.340,2026-06-11T17:14:41,86,3454,3540,NaN

## Просмотр csv файлов

In [4]:
df_qwen3535b = pd.read_csv("qwenqwen3535b_answers.csv", encoding="utf-8-sig")

In [5]:
df_qwen3535b.head(2)

,id,domain,source_type,source_id,source_url,question_type,difficulty,question,context,expected_answer,...,manual_final_score,manual_comment,model,temperature,latency_sec,created_at,prompt_tokens,completion_tokens,total_tokens,error
0,habr_879914_001,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое массив и как его элементы располагаю...,Раздел про массивы.,Массив хранит элементы одного типа в непрерывн...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0,58.710,2026-06-09T17:33:21,79.0,3988.0,4067.0,NaN
1,habr_879914_002,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,reasoning,medium,Почему доступ к элементу массива по индексу об...,Раздел про массивы и операции с ними.,Потому что адрес элемента можно вычислить напр...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0,95.065,2026-06-09T17:34:56,92.0,6560.0,6652.0,NaN

In [6]:
df_qwen3535b.columns

Index(['id', 'domain', 'source_type', 'source_id', 'source_url',
       'question_type', 'difficulty', 'question', 'context', 'expected_answer',
       'scoring_rubric', 'model_answer', 'ragas_factual_correctness',
       'ragas_semantic_similarity', 'ragas_final_score', 'manual_final_score',
       'manual_comment', 'model', 'temperature', 'latency_sec', 'created_at',
       'prompt_tokens', 'completion_tokens', 'total_tokens', 'error'],
      dtype='str')

In [3]:
df_qwenqwen_test = pd.read_csv("qwenqwen3535b_answers_ragas_test.csv", encoding="utf-8-sig")

In [4]:
df_qwenqwen_test.head(2)

,id,domain,source_type,source_id,source_url,question_type,difficulty,question,context,expected_answer,...,manual_final_score,manual_comment,model,temperature,latency_sec,created_at,prompt_tokens,completion_tokens,total_tokens,error
0,habr_879914_001,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое массив и как его элементы располагаю...,Раздел про массивы.,Массив хранит элементы одного типа в непрерывн...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0,58.710,2026-06-09T17:33:21,79.0,3988.0,4067.0,NaN
1,habr_879914_002,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,reasoning,medium,Почему доступ к элементу массива по индексу об...,Раздел про массивы и операции с ними.,Потому что адрес элемента можно вычислить напр...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0,95.065,2026-06-09T17:34:56,92.0,6560.0,6652.0,NaN

In [5]:
df_qwenqwen_test.to_excel("qwen3535b_ragas_test.xlsx", index=False)