In [3]:
import numpy as np
import pandas as pd

In [4]:
from openai import OpenAI

In [5]:
client = OpenAI(
    base_url="http://192.168.15.182:1234/v1",
    api_key="sk-no-key-required"
)

In [ ]:
response = client.chat.completions.create(
    model="qwen/qwen3.5-35b-a3b",
    messages=[
        {"role": "user", "content": "Привет! Напиши одно короткое приветствие."}
    ]
)

In [ ]:
print(response.choices[0].message.content)

In [7]:
df_questions = pd.read_csv("questions.csv")

In [8]:
df_questions.head()

,id,domain,source_type,source_id,source_url,question,context,expected_answer,question_type,difficulty,scoring_rubric
0,habr_879914_001,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,Что такое массив и как его элементы располагаю...,Раздел про массивы.,Массив хранит элементы одного типа в непрерывн...,factual,easy,NaN
1,habr_879914_002,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,Почему доступ к элементу массива по индексу об...,Раздел про массивы и операции с ними.,Потому что адрес элемента можно вычислить напр...,reasoning,medium,NaN
2,habr_879914_003,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,В чем основное отличие статического массива от...,Раздел про массивы.,"Статический массив имеет фиксированный размер,...",comparison,easy,NaN
3,habr_879914_004,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,Почему вставка элемента в середину массива обы...,Раздел про массивы и стоимость операций.,При вставке в середину нужно сдвигать последую...,reasoning,medium,NaN
4,habr_879914_005,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,Что такое связный список и из чего состоит его...,Раздел про связные списки.,Связный список состоит из узлов; каждый узел х...,factual,easy,NaN

In [10]:
df_questions.difficulty.value_counts()

difficulty
easy      15
medium    14
hard       1
Name: count, dtype: int64

In [15]:
df_answers = pd.read_csv("model_answers.csv")

In [16]:
df_answers

,id,domain,source_type,source_id,source_url,question_type,difficulty,question,context,expected_answer,...,final_score,judge_explanation,model,temperature,latency_sec,created_at,prompt_tokens,completion_tokens,total_tokens,error
0,habr_879914_001,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое массив и как его элементы располагаю...,Раздел про массивы.,Массив хранит элементы одного типа в непрерывн...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,58.710,2026-06-09T17:33:21,79.0,3988.0,4067.0,NaN
1,habr_879914_002,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,reasoning,medium,Почему доступ к элементу массива по индексу об...,Раздел про массивы и операции с ними.,Потому что адрес элемента можно вычислить напр...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,95.065,2026-06-09T17:34:56,92.0,6560.0,6652.0,NaN
2,habr_879914_003,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,comparison,easy,В чем основное отличие статического массива от...,Раздел про массивы.,"Статический массив имеет фиксированный размер,...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,78.648,2026-06-09T17:36:15,82.0,5410.0,5492.0,NaN
3,habr_879914_004,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,reasoning,medium,Почему вставка элемента в середину массива обы...,Раздел про массивы и стоимость операций.,При вставке в середину нужно сдвигать последую...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,39.321,2026-06-09T17:36:54,92.0,2646.0,2738.0,NaN
4,habr_879914_005,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое связный список и из чего состоит его...,Раздел про связные списки.,Связный список состоит из узлов; каждый узел х...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,115.972,2026-06-09T17:38:50,82.0,8024.0,8106.0,NaN
5,habr_879914_006,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,application,medium,В какой ситуации связный список может быть удо...,Раздел про сравнение массивов и списков.,"Связный список удобен, когда важны частые вста...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,84.932,2026-06-09T17:40:15,84.0,5850.0,5934.0,NaN
6,habr_879914_007,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,reasoning,medium,Почему доступ к произвольному элементу связног...,Раздел про связные списки и операции.,"Потому что элементы не лежат подряд в памяти, ...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,39.652,2026-06-09T17:40:54,90.0,2661.0,2751.0,NaN
7,habr_879914_008,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,comparison,easy,Чем односвязный список отличается от двусвязного?,Раздел про разновидности связных списков.,В односвязном списке узел содержит ссылку толь...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,120.022,2026-06-09T17:42:54,NaN,NaN,NaN,hard_timeout_after_120.0_seconds
8,habr_879914_009,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое стек и какой принцип работы он испол...,Раздел про стек.,Стек — структура данных с принципом LIFO: посл...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,36.940,2026-06-09T17:43:31,76.0,2470.0,2546.0,NaN
9,habr_879914_010,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Какие базовые операции обычно есть у стека?,Раздел про стек и его операции.,Обычно у стека есть операции push для добавлен...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,65.221,2026-06-09T17:44:37,81.0,4481.0,4562.0,NaN
10,habr_879914_011,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,application,medium,"Приведи пример задачи, где естественно использ...",Раздел про применение стека.,Стек естественно использовать для обработки ск...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,70.426,2026-06-09T17:45:47,79.0,4835.0,4914.0,NaN
11,habr_879914_012,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое очередь и какой принцип работы она и...,Раздел про очередь.,Очередь — структура данных с принципом FIFO: п...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,35.611,2026-06-09T17:46:23,76.0,2384.0,2460.0,NaN
12,habr_879914_013,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,comparison,easy,Чем очередь отличается от стека?,Разделы про стек и очередь.,"Стек работает по принципу LIFO, а очередь — по...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,61.160,2026-06-09T17:47:24,76.0,4190.0,4266.0,NaN
13,habr_879914_014,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,application,medium,Для чего может использоваться очередь в програ...,Раздел про применение очереди.,"Очередь используется для планирования задач, о...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,89.357,2026-06-09T17:48:53,76.0,6163.0,6239.0,NaN
14,habr_879914_015,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое хеш-таблица?,Раздел про хеш-таблицы.,Хеш-таблица хранит пары ключ-значение и исполь...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,48.293,2026-06-09T17:49:41,80.0,3278.0,3358.0,NaN
15,habr_879914_016,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,reasoning,medium,"Почему операции поиска, вставки и удаления в х...",Раздел про хеш-таблицы и сложность операций.,В среднем хеш-функция быстро переводит ключ в ...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,80.443,2026-06-09T17:51:02,101.0,5522.0,5623.0,NaN
16,habr_879914_017,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое коллизия в хеш-таблице?,Раздел про хеш-таблицы.,"Коллизия возникает, когда разные ключи дают од...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,67.197,2026-06-09T17:52:09,86.0,4603.0,4689.0,NaN
17,habr_879914_018,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,medium,Какими способами можно обрабатывать коллизии в...,Раздел про хеш-таблицы и коллизии.,"Коллизии можно обрабатывать цепочками, открыто...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,83.746,2026-06-09T17:53:33,95.0,5776.0,5871.0,NaN
18,habr_879914_019,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,medium,Что такое куча как структура данных?,Раздел про кучи.,Куча — это обычно бинарное дерево или массивно...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,120.026,2026-06-09T17:55:33,NaN,NaN,NaN,hard_timeout_after_120.0_seconds
19,habr_879914_020,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,comparison,easy,Чем min-heap отличается от max-heap?,Раздел про кучи.,В min-heap каждый родитель не больше своих пот...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,74.038,2026-06-09T17:56:47,79.0,5081.0,5160.0,NaN
20,habr_879914_021,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,application,medium,Почему куча удобна для реализации очереди с пр...,Раздел про кучи и применение.,Куча позволяет быстро получать элемент с миним...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,70.703,2026-06-09T17:57:58,87.0,4826.0,4913.0,NaN
21,habr_879914_022,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое дерево в контексте структур данных?,Раздел про деревья.,Дерево — иерархическая структура из узлов и ре...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,51.380,2026-06-09T17:58:49,75.0,3492.0,3567.0,NaN
22,habr_879914_023,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое бинарное дерево?,Раздел про деревья.,"Бинарное дерево — дерево, в котором у каждого ...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,92.368,2026-06-09T18:00:21,73.0,6353.0,6426.0,NaN
23,habr_879914_024,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,comparison,medium,Что отличает бинарное дерево поиска от обычног...,Раздел про бинарное дерево поиска.,В бинарном дереве поиска левое поддерево содер...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,564.341,2026-06-09T18:09:46,85.0,6798.0,6883.0,NaN
24,habr_879914_025,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,reasoning,medium,Почему несбалансированное бинарное дерево поис...,Раздел про деревья и эффективность поиска.,"Если дерево вырождается в цепочку, поиск, вста...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,98.710,2026-06-09T18:11:24,87.0,6801.0,6888.0,NaN
25,habr_879914_026,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,easy,Что такое граф?,Раздел про графы.,"Граф — структура данных из вершин и ребер, опи...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,57.948,2026-06-09T18:12:22,72.0,3908.0,3980.0,NaN
26,habr_879914_027,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,comparison,easy,Чем ориентированный граф отличается от неориен...,Раздел про графы.,В ориентированном графе ребра имеют направлени...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,76.781,2026-06-09T18:13:39,85.0,5259.0,5344.0,NaN
27,habr_879914_028,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,factual,medium,Какими способами можно представить граф в памяти?,Раздел про представление графов.,Граф можно представить матрицей смежности или ...,...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,92.365,2026-06-09T18:15:12,78.0,6350.0,6428.0,NaN
28,habr_879914_029,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,application,medium,Когда матрица смежности может быть удобнее спи...,Раздел про представление графов.,"Матрица смежности удобна, когда нужно быстро п...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,174.311,2026-06-09T18:18:06,NaN,NaN,NaN,hard_timeout_after_120.0_seconds
29,habr_879914_030,data_structures,article,habr_879914,https://habr.com/ru/articles/879914/,multi_hop,hard,Какие структуры данных из статьи лучше всего п...,"Обобщающий вопрос по хеш-таблицам, очередям и ...","Для поиска по ключу подходит хеш-таблица, для ...",...,NaN,NaN,qwen/qwen3.5-35b-a3b,0.0,67.397,2026-06-09T18:19:13,114.0,4634.0,4748.0,NaN

In [17]:
df_answers.to_excel("llm_answers_30.xlsx", index=False)

In [20]:
df_ans_scored = pd.read_csv("llm_answers_30_scored.csv", sep=';')

In [27]:
df_ans_scored.final_score

0     2,00
1     2,00
2     2,00
3     2,00
4     2,00
5     2,00
6     2,00
7     0,00
8     2,00
9     2,00
10    2,00
11    0,00
12    2,00
13    2,00
14    2,00
15    2,00
16    2,00
17    2,00
18    0,00
19    2,00
20    2,00
21    0,00
22    2,00
23    0,00
24    2,00
25    0,00
26    1,00
27    2,00
28    0,00
29    2,00
Name: final_score, dtype: str

In [28]:
df_ans_scored.to_excel("answers_30.xlsx", index=False)